name: CI
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig-version: [0.8.0, 0.9.0, 0.10.1, master]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{matrix.zig-version}}
      - name: Run tests
        run: zig build test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.9.0
      - name: Check code style
        run: zig fmt --check src/*.zig
